name: Build

# Controls when the action will run.
on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: build files
        run: npx astro build

      - name: keep static files only
        run: |
          mkdir -p base
          cp -r dist/* base/
          find . -maxdepth 1 ! -name base ! -name .git ! -name . ! -name .. -exec rm -rf {} +
          mv base/* .
          rm -rf base

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Copy dist to base and clean up"
          git push orign build
